import { Agent, Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'images',
    name: 'Creación de Imágenes',
    description: 'Genera imágenes especializadas para diferentes propósitos',
    icon: 'image',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'writing',
    name: 'Redacción y Contenido',
    description: 'Crea contenido profesional para cualquier necesidad',
    icon: 'pen-tool',
    color: 'from-slate-700 to-slate-900',
  },
  {
    id: 'code',
    name: 'Desarrollo y Código',
    description: 'Asistencia experta en programación y desarrollo',
    icon: 'code',
    color: 'from-green-600 to-emerald-600',
  },
  {
    id: 'data',
    name: 'Análisis de Datos',
    description: 'Procesa y analiza información compleja',
    icon: 'bar-chart',
    color: 'from-orange-600 to-red-600',
  },
  {
    id: 'social',
    name: 'Redes Sociales',
    description: 'Optimiza tu presencia en redes sociales',
    icon: 'share-2',
    color: 'from-pink-600 to-rose-600',
  },
  {
    id: 'video',
    name: 'Video y Multimedia',
    description: 'Crea y edita contenido audiovisual',
    icon: 'video',
    color: 'from-amber-600 to-yellow-600',
  },
];

export const AGENTS: Agent[] = [
  {
    id: 'commercial-images',
    name: 'Imágenes Comerciales',
    description: 'Genera imágenes profesionales para publicidad y marketing',
    icon: 'shopping-bag',
    model: 'gemini',
    categoryId: 'images',
  },
  {
    id: 'product-photography',
    name: 'Fotografía de Productos',
    description: 'Crea renders fotorrealistas de productos para e-commerce',
    icon: 'package',
    model: 'gemini',
    categoryId: 'images',
  },
  {
    id: 'automotive-images',
    name: 'Imágenes Automotrices',
    description: 'Especializado en renderizados de autos y vehículos',
    icon: 'car',
    model: 'gemini',
    categoryId: 'images',
  },
  {
    id: 'real-estate-images',
    name: 'Imágenes Inmobiliarias',
    description: 'Visualizaciones arquitectónicas y de propiedades',
    icon: 'home',
    model: 'gemini',
    categoryId: 'images',
  },
  {
    id: 'food-photography',
    name: 'Fotografía Gastronómica',
    description: 'Imágenes apetitosas de alimentos y bebidas',
    icon: 'utensils',
    model: 'gemini',
    categoryId: 'images',
  },
  {
    id: 'fashion-images',
    name: 'Imágenes de Moda',
    description: 'Genera looks y outfits para fashion y retail',
    icon: 'shirt',
    model: 'gemini',
    categoryId: 'images',
  },
  {
    id: 'email-writer',
    name: 'Redactor de Emails',
    description: 'Emails profesionales para negocios, ventas y soporte',
    icon: 'mail',
    model: 'openai',
    categoryId: 'writing',
  },
  {
    id: 'blog-writer',
    name: 'Escritor de Blogs',
    description: 'Artículos SEO-optimizados y engaging para tu blog',
    icon: 'file-text',
    model: 'openai',
    categoryId: 'writing',
  },
  {
    id: 'copywriter',
    name: 'Copywriter',
    description: 'Copy persuasivo para anuncios y landing pages',
    icon: 'target',
    model: 'openai',
    categoryId: 'writing',
  },
  {
    id: 'script-writer',
    name: 'Guionista',
    description: 'Scripts para videos, podcasts y presentaciones',
    icon: 'film',
    model: 'openai',
    categoryId: 'writing',
  },
  {
    id: 'technical-writer',
    name: 'Escritor Técnico',
    description: 'Documentación técnica clara y precisa',
    icon: 'book-open',
    model: 'openai',
    categoryId: 'writing',
  },
  {
    id: 'translator',
    name: 'Traductor',
    description: 'Traducciones precisas manteniendo el contexto',
    icon: 'languages',
    model: 'openai',
    categoryId: 'writing',
  },
  {
    id: 'fullstack-dev',
    name: 'Desarrollador Full Stack',
    description: 'Asistencia en frontend, backend y arquitectura',
    icon: 'code-2',
    model: 'openai',
    categoryId: 'code',
  },
  {
    id: 'react-specialist',
    name: 'Especialista React',
    description: 'Expert en React, Next.js y ecosistema moderno',
    icon: 'component',
    model: 'openai',
    categoryId: 'code',
  },
  {
    id: 'python-dev',
    name: 'Desarrollador Python',
    description: 'Python, Django, FastAPI y machine learning',
    icon: 'terminal',
    model: 'openai',
    categoryId: 'code',
  },
  {
    id: 'devops-engineer',
    name: 'Ingeniero DevOps',
    description: 'CI/CD, Docker, Kubernetes y cloud',
    icon: 'cloud',
    model: 'openai',
    categoryId: 'code',
  },
  {
    id: 'code-reviewer',
    name: 'Revisor de Código',
    description: 'Code review y mejores prácticas de desarrollo',
    icon: 'search-code',
    model: 'openai',
    categoryId: 'code',
  },
  {
    id: 'bug-hunter',
    name: 'Cazador de Bugs',
    description: 'Debugging y resolución de problemas técnicos',
    icon: 'bug',
    model: 'openai',
    categoryId: 'code',
  },
  {
    id: 'data-analyst',
    name: 'Analista de Datos',
    description: 'Analiza datasets y genera insights accionables',
    icon: 'trending-up',
    model: 'openai',
    categoryId: 'data',
  },
  {
    id: 'business-intelligence',
    name: 'Business Intelligence',
    description: 'Métricas de negocio y KPIs estratégicos',
    icon: 'line-chart',
    model: 'openai',
    categoryId: 'data',
  },
  {
    id: 'financial-analyst',
    name: 'Analista Financiero',
    description: 'Análisis financiero y proyecciones',
    icon: 'dollar-sign',
    model: 'openai',
    categoryId: 'data',
  },
  {
    id: 'market-researcher',
    name: 'Investigador de Mercado',
    description: 'Research de mercado y análisis competitivo',
    icon: 'briefcase',
    model: 'openai',
    categoryId: 'data',
  },
  {
    id: 'excel-expert',
    name: 'Experto en Excel',
    description: 'Fórmulas, tablas dinámicas y automatización',
    icon: 'table',
    model: 'openai',
    categoryId: 'data',
  },
  {
    id: 'instagram-creator',
    name: 'Creador Instagram',
    description: 'Posts y stories optimizados para Instagram',
    icon: 'instagram',
    model: 'openai',
    categoryId: 'social',
  },
  {
    id: 'linkedin-writer',
    name: 'Escritor LinkedIn',
    description: 'Contenido profesional para LinkedIn',
    icon: 'linkedin',
    model: 'openai',
    categoryId: 'social',
  },
  {
    id: 'twitter-expert',
    name: 'Experto en Twitter',
    description: 'Tweets virales y threads engaging',
    icon: 'twitter',
    model: 'openai',
    categoryId: 'social',
  },
  {
    id: 'tiktok-creator',
    name: 'Creador TikTok',
    description: 'Ideas y scripts para videos de TikTok',
    icon: 'music',
    model: 'openai',
    categoryId: 'social',
  },
  {
    id: 'social-media-manager',
    name: 'Social Media Manager',
    description: 'Estrategia y calendario de contenido',
    icon: 'calendar',
    model: 'openai',
    categoryId: 'social',
  },
  {
    id: 'video-editor',
    name: 'Editor de Video',
    description: 'Guías de edición y efectos para videos',
    icon: 'scissors',
    model: 'openai',
    categoryId: 'video',
  },
  {
    id: 'youtube-creator',
    name: 'Creador YouTube',
    description: 'Ideas, títulos y descripciones para YouTube',
    icon: 'youtube',
    model: 'openai',
    categoryId: 'video',
  },
  {
    id: 'animation-expert',
    name: 'Experto en Animación',
    description: 'Conceptos y storyboards para animaciones',
    icon: 'zap',
    model: 'gemini',
    categoryId: 'video',
  },
  {
    id: 'podcast-producer',
    name: 'Productor de Podcast',
    description: 'Guiones y estructura para podcasts',
    icon: 'mic',
    model: 'openai',
    categoryId: 'video',
  },
];
